* Java implementation of IB CS abstract data types
** IB abstract data types in Java programs
   This repository contains Java classes that implement abstract data
   types used in IB Computer Science. Currently only collections are
   implemented; other data types (stacks, queues) will follow.

** Usage
   1. Clone this repository into your project directory by running
      #+begin_src sh
      git clone https://github.com/jarmohurri/ibadts.git
      #+end_src
      or, if you are using =git= yourself in your project, add this
      library as a submodule
      #+begin_src sh
      git submodule add https://github.com/jarmohurri/ibadts.git
      #+end_src
   2. Example use of a collection.
      #+begin_src java :exports none :classname CollectionExample :results output 
        import ibadts.IBCollection;

        class CollectionExample
        {
          public static void main (String[] args)
          {
            // construction using Integer (with autoboxing)
            IBCollection temps = new IBCollection <Integer> ();

            temps.add (new Integer[] {19, 22}); // initialize from array
            temps.addItem (-5); // add one more

            temps.resetNext (); // go to start
            // traverse
            while (temps.hasNext ())
              System.out.println (temps.getNext ()); 
          }
        }
      #+end_src

      #+RESULTS:
      : 19
      : 22
      : -5

** License
   Copyright (C) 2020 Jarmo Hurri

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
