* Java implementation of IB CS abstract data types
** IB abstract data types in Java programs
   This repository contains Java classes that implement abstract data
   types used in IB Computer Science. Currently only collections are
   implemented; other data types (stacks, queues) will follow.

** Usage
   1. Clone this repository into your project directory by running
      #+begin_src sh
      git clone https://github.com/jarmohurri/ibadts.git
      #+end_src
      or, if you are using =git= yourself in your project, add this
      library as a submodule
      #+begin_src sh
      git submodule add https://github.com/jarmohurri/ibadts.git
      #+end_src
   2. Example use of a collection.
      #+begin_src java :exports both :classname CollectionExample :results output 
        import ibadts.IBCollection;

        class CollectionExample
        {
          public static void main (String[] args)
          {
            // construction using Integer (with autoboxing)
            IBCollection temps = new IBCollection <Integer> ();

            temps.add (new Integer[] {19, 22}); // initialize from array
            temps.addItem (-5); // add one more

            temps.resetNext (); // go to start
            // traverse
            while (temps.hasNext ())
              System.out.println (temps.getNext ()); 
          }
        }
      #+end_src

      #+RESULTS:
      : 19
      : 22
      : -5
   3. Example use of a stack.
      #+begin_src java :exports both :classname StackExample :results output 
        import ibadts.IBStack;

        class StackExample
        {
          public static void main (String[] args)
          {
            IBStack bits = new IBStack <String> ();
            int decimal = 1216;
    
            while (decimal > 0)
            {
              String digit;
              if (decimal % 2 == 0)
                digit = "zero";
              else
                digit = "one";
              bits.push (digit);
              decimal = decimal / 2;
            }
            while (!bits.isEmpty ())
              System.out.print (bits.pop () + " ");
          }
        }
      #+end_src

      #+RESULTS:
      : one zero zero one one zero zero zero zero zero zero
   4. Example use of queue.
      #+begin_src java :exports both :classname QueueExample :results output 
        import ibadts.IBQueue;

        class QueueExample
        {
          public static void main (String[] args)
          {
            IBQueue line = new IBQueue <String> ();
            for (int i = 0; i < 10; i++)
              line.enqueue ("slow customer " + i);
            line.enqueue ("hungry me");
            while (!line.isEmpty ())
              System.out.println ("Next! -> food for " + line.dequeue ());
          }
        }
      #+end_src

      #+RESULTS:
      #+begin_example
      Next! -> food for slow customer 0
      Next! -> food for slow customer 1
      Next! -> food for slow customer 2
      Next! -> food for slow customer 3
      Next! -> food for slow customer 4
      Next! -> food for slow customer 5
      Next! -> food for slow customer 6
      Next! -> food for slow customer 7
      Next! -> food for slow customer 8
      Next! -> food for slow customer 9
      Next! -> food for hungry me
      #+end_example
      

** License
   Copyright (C) 2020 Jarmo Hurri

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
